import random
import os
import time
print("auth.co")
print ("---------------------")
print("Welcome to Quicklife Inc.!")
print("Username:")
input1 = input()
os.system('cls') 
print("Password:")
input3 = input()
os.system('cls') 
time.sleep(5)
print("Welcome back, "+ input1 +"!")
time.sleep(1.5)
os.system('cls')
print("You currently have two-auth on, please choose an option")
print("1. AMP Connectivity Code")
print("2. One-time Password")
print("3. Auth2.com")
print("4. auth.co")
input2 = input()
if input2 == "1":
    print("Redirecting....")
    time.sleep(0.5)
    os.system('cls')
    time.sleep(2.5)
    print("Username:")
    input()
    print("Password:")
    input()
    os.system('cls')
    time.sleep(3)
    print("Redirecting....")
if input2 == "2":
    print("Please enter your one-time password")
    input()
    random1 = random.randint(1,2)
    if random1 == 1:
        os.system('cls')
        time.sleep(3)
        print("Redirecting....")
    if random1 == 2:
        os.system('cls')
        time.sleep(3)
        print("Error: incorrect password. Please restart the program")
        input()

