import random
import time
import os

random = random.randint(1,2)

if random == 1 :
    print("Hello! Welcome to the setup of Your New Computer!")
    ask1 = input("Do you already have an exsisting account? (Write y or n)")
    if ask1 == "y":
        os.system('cls')
        time.sleep(2)
        ask2 = input("Username:")
        ask3 = input("Password:")
        os.system('cls')
        print("Welcome back, " + ask2 + ".")
        time.sleep(1.5)
        os.system('cls')
        ask4 = input("Do you want to make your whole computer °75 or just download the app? (Write pc or app)")
        if ask4 == "pc":
            os.system('cls')
            time.sleep(2)
            print("We made a folder named '°75'. Burn the .iso file in it to a DVD. It should bring to your DVD. ")
            print("Double-click the setup.exe to setup your computer.")
            end = input("Press Enter to continue.")
        elif ask4 == "app":
            os.system('cls')
            print("Downloading.. 0%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..5%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..10%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..15%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..20%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..37%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..49%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..86%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..92%")
            time.sleep(1.5)
            os.system('cls')
            print("Downloading..100%")
            time.sleep(1.5)
            os.system('cls')
            print("Done! Check your desktop!")
            end = input("Press Enter to continue.")
        else :
           print("Invalid")
           end = input("Press Enter to continue.")
    elif ask1 == "n":
     print("Test")   
    else :
        print("Invalid")
        end = input("Press Enter to continue.")
else :
    print ("Error! Error Code: 01382401")
    print ("If you want to troubleshoot, search this code in www.seventy-five.com")
    print ("Restarting...")
    time.sleep(5)
    print("Cannot restart. Trying again. (1)")
    time.sleep(5)
    print("Cannot restart. Trying again. (2)")
    time.sleep(5)
    print("Cannot restart. Trying again. (3)")
    time.sleep(5)
    print("Cannot restart. Trying again. (4)")
    time.sleep(5)
    print("Cannot restart. Trying again. (5)")
    time.sleep(5)
    end = input("Please manually restart the program.")
    
    
