from tkinter import *
window=Tk()
# add widgets here
btn=Button(window, text="This is a button", fg='red')
btn.place(x=80, y=100)
btn=Button(window, text="This is a button", fg='red')
btn.place(x=180, y=100)
btn=Button(window, text="This is a button", fg='red')
btn.place(x=280, y=100)
lbl=Label(window, text="This is a Label widget", fg='red', font=("Helvetica", 16))
lbl.place(x=60, y=50)
txtfld=Entry(window, text="This is Entry Widget", bd=5)
txtfld.place(x=80, y=150)
v0=IntVar()
v0.set(1)
r1=Radiobutton(window, text="male", variable=v0,value=1)
r2=Radiobutton(window, text="female", variable=v0,value=2)
r1.place(x=100,y=200)
r2.place(x=180, y=200)
v1 = IntVar()
v2 = IntVar()
C1 = Checkbutton(window, text = "Cricket", variable = v1)
C2 = Checkbutton(window, text = "Tennis", variable = v2)
C1.place(x=100, y=250)
C2.place(x=180, y=250)
window.title('Hello Python')
window.geometry("500x300+20+30")
window.mainloop()
